### ISSUE TITLE
404: A Practical Introduction to Async Programming in Rust

### ISSUE THREAD

**Issue by legends2k** [jamesmcm/jamesmcm.github.io#1]
[This piece](http://jamesmcm.github.io/blog/2020/05/06/a-practical-introduction-to-async-programming-in-rust/#en) is missing.  Was it removed intentionally or fell through the cracks when migrating to Zola?

**Comment by jamesmcm** [comment]
https://jamesmcm.github.io/blog/a-practical-introduction-to-async-programming-in-rust/

The URL changed - where did you find the old link btw?

**Comment by legends2k** [comment]
> Where did you find the old link btw?

https://jamesmcm.github.io/blog/programming-projects/ under _TCP client/server or proxy_ section.

Thanks for the write-up :)

**Comment by jamesmcm** [comment]
Thanks, I'll fix it!
